### ISSUE TITLE
这个项目的完成情况怎么样

### ISSUE THREAD

**Issue by geffzhang** [zlzforever/Swarm#1]
今天突然看到这个项目，看到项目更新也就是最近2天，想问下当前项目进展怎么样？

**Comment by zlzforever** [comment]
做了第三周了，暂时不建议生产使用，还有很多细节要处理，不成熟。如果只是几百个甚至几万个任务调度直接使用quartz.net即可，没有必要使用这个。项目初衷是如果调度任务达到了如阿里的SchedulerX这样几十万上百万的任务调度如何解决精准触发的问题。后面可能也会往DAG上做支持。只是个设想中的项目

**Comment by geffzhang** [comment]
可以一起来开发呀，有没有设计文档

**Comment by zlzforever** [comment]
我稍后写一下大概的思路、设计。提交好了@您

**Comment by zlzforever** [comment]
https://github.com/zlzforever/Swarm/blob/master/DESIGN.md
@geffzhang 初步思路,　不确定这个项目有没有实际应用场景

**Comment by geffzhang** [comment]
有应用场景呀，这个很不错的思路
